
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Luis Trejo
 */
public class SeleccionMaterias extends javax.swing.JFrame {

    DefaultTableModel modelo;
    String[] sArrayListaMateSele;
    int contadorMaterias = 0;

    /**
     * Creates new form SeleccionMaterias
     */
    public SeleccionMaterias() {

        initComponents();
        sArrayListaMateSele = new String[6];

        modelo = new DefaultTableModel();
        tablaSemestres.setModel(modelo);

        modelo.addColumn("SEMESTRE 1");
        modelo.addColumn("SEMESTRE 2");
        modelo.addColumn("SEMESTRE 3");
        modelo.addColumn("SEMESTRE 4");
        modelo.addColumn("SEMESTRE 5");
        modelo.addColumn("SEMESTRE 6");
        modelo.addColumn("SEMESTRE 7");
        modelo.addColumn("SEMESTRE 8");
        modelo.addColumn("SEMESTRE 9");

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/horarios_isc_enero", "root", "pass");
            int contador = 0;
            for (int i = 1; i < 9; i++) {
                PreparedStatement updateemp = con.prepareStatement("SELECT * FROM carga_semestral WHERE Clave LIKE ?");
                updateemp.setString(1, i + "P%");
                ResultSet rs = updateemp.executeQuery();
                Object[] object = new Object[9];
                int num = 0;
                while (rs.next()) {
                    System.out.println(rs.getString("Clave") + " - " + rs.getString("materia"));
                    object[num] = rs.getString("materia");
                    num++;

                }
                modelo.addRow(object);

                //contador = contador + 1;       
                System.out.println("--------------------");
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        SpinnerNumberModel nm = new SpinnerNumberModel();
        nm.setValue(7);
        nm.setMaximum(20);
        nm.setMinimum(7);
        spiHoras.setModel(nm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSemestres = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAMateSeleccionadas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spiHoras = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        bntContinuar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaSemestres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaSemestres.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaSemestres.setDragEnabled(true);
        tablaSemestres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSemestresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSemestres);

        txtAMateSeleccionadas.setColumns(20);
        txtAMateSeleccionadas.setRows(5);
        jScrollPane3.setViewportView(txtAMateSeleccionadas);

        jLabel1.setText("Materias Seleccionadas:");

        jLabel2.setText("Hora de inicio:");

        jLabel3.setText("Hrs");

        bntContinuar.setText("Generar");
        bntContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spiHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntContinuar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(spiHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntContinuar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaSemestresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSemestresMouseClicked
        // TODO add your handling code here:
        int fila = tablaSemestres.rowAtPoint(evt.getPoint());
        int columna = tablaSemestres.columnAtPoint(evt.getPoint());
        if ((fila > -1) && (columna > -1)) {
            //System.out.println(modelo.getValueAt(fila, columna));
            if (contadorMaterias <= 5) {
                sArrayListaMateSele[contadorMaterias] = modelo.getValueAt(fila, columna).toString();
                txtAMateSeleccionadas.append(sArrayListaMateSele[contadorMaterias] + '\n');
                contadorMaterias++;

            } else {
                JOptionPane.showMessageDialog(rootPane, "Limite maximo de materias a seleccionar: 6", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
            //for (int i = 0; i < sArrayListaMateSele.length; i++) {
            //    System.out.println(sArrayListaMateSele[i]);
            //}
            System.out.println(contadorMaterias);
        }

    }//GEN-LAST:event_tablaSemestresMouseClicked

    private void bntContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntContinuarActionPerformed
        // TODO add your handling code here:
        Busqueda busqueda = new Busqueda();
        busqueda.setsArrayMateSele(sArrayListaMateSele);
        busqueda.setiHora(Integer.parseInt(spiHoras.getValue().toString()));
        busqueda.conectar();
    }//GEN-LAST:event_bntContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionMaterias().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JSpinner spiHoras;
    private javax.swing.JTable tablaSemestres;
    private javax.swing.JTextArea txtAMateSeleccionadas;
    // End of variables declaration//GEN-END:variables
}
